import type { Metadata } from "next";
import FaqClient from "./FaqClient";

export const metadata: Metadata = {
  title: "Website Speed FAQ — Common Questions About Page Load Time",
  description: "Answers to the most common questions about website speed, Core Web Vitals, above-the-fold load time, and what a 1-second load time means for your local business.",
  alternates: { canonical: "https://pingclose.com/faq" },
  openGraph: {
    title: "Website Speed FAQ | PingClose",
    description: "Common questions about website speed, Core Web Vitals, and what a 1-second load time means for your local business.",
    url: "https://pingclose.com/faq",
  },
};

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [
    { "@type": "Question", "name": "Why is my website slow?", "acceptedAnswer": { "@type": "Answer", "text": "The most common causes of a slow website are unoptimized images, cheap shared hosting, render-blocking JavaScript, no caching, and too many third-party scripts. Most local business websites fail on at least 3 of these simultaneously — and the business owner has no idea until a customer leaves and never comes back." } },
    { "@type": "Question", "name": "How do I check my website speed for free?", "acceptedAnswer": { "@type": "Answer", "text": "Google PageSpeed Insights is the most authoritative free tool for checking website speed — it uses the same data Google uses for ranking decisions. GTmetrix, Pingdom, and DebugBear also offer free speed tests. Enter your URL, run the test on mobile, and focus on Core Web Vitals scores rather than the overall performance number." } },
    { "@type": "Question", "name": "What is a good Google PageSpeed score?", "acceptedAnswer": { "@type": "Answer", "text": "A score of 90 or above is considered good by Google. Scores between 50–89 need improvement, and below 50 is poor. However, Google ranks based on Core Web Vitals — not the overall score. A site scoring 72 with good Core Web Vitals will outrank a site scoring 85 with poor ones." } },
    { "@type": "Question", "name": "What is Core Web Vitals?", "acceptedAnswer": { "@type": "Answer", "text": "Core Web Vitals are three specific speed measurements Google uses as ranking factors: LCP (how fast the main content loads), INP (how fast the page responds to clicks), and CLS (how much the page jumps around while loading). Google confirmed these as official ranking signals in 2021." } },
    { "@type": "Question", "name": "How fast should a website load in 2026?", "acceptedAnswer": { "@type": "Answer", "text": "Google's standard is under 2.5 seconds for LCP on mobile. The real competitive benchmark is under 1 second for initial page response. Websites loading in 1 second convert at 40%. By 3 seconds that drops to 29%. Every second costs you customers and search rankings simultaneously." } },
    { "@type": "Question", "name": "What is LCP and why does it matter?", "acceptedAnswer": { "@type": "Answer", "text": "LCP stands for Largest Contentful Paint — the time it takes for the biggest visible element on your page to fully load. Google considers under 2.5 seconds good, 2.5–4 seconds needs improvement, and over 4 seconds poor. It is one of three Core Web Vitals Google uses as ranking factors." } },
    { "@type": "Question", "name": "What is TTFB?", "acceptedAnswer": { "@type": "Answer", "text": "TTFB stands for Time to First Byte — how long it takes a server to respond after a browser requests a page. Under 600ms is considered good. A high TTFB usually means hosting is too slow, the server is overloaded, or caching is not configured. It is the first speed measurement in the loading chain." } },
    { "@type": "Question", "name": "What causes a slow loading website?", "acceptedAnswer": { "@type": "Answer", "text": "The top causes of slow websites are unoptimized images, cheap shared hosting, render-blocking JavaScript and CSS, no browser caching, too many third-party scripts, and a poorly configured content delivery network. Most slow local business sites have four to six of these problems simultaneously." } },
    { "@type": "Question", "name": "How do I fix a slow WordPress site?", "acceptedAnswer": { "@type": "Answer", "text": "To fix a slow WordPress site: convert images to WebP format, install a caching plugin, upgrade hosting, remove unused plugins, defer render-blocking JavaScript, and enable a CDN. These fixes together can improve a WordPress mobile score from 35 to 85 and cut load time in half." } },
    { "@type": "Question", "name": "Does website speed affect Google ranking?", "acceptedAnswer": { "@type": "Answer", "text": "Yes. Google confirmed page speed as a ranking factor in 2010 and made Core Web Vitals an official ranking signal in 2021. Slow sites rank below faster competitors when all other factors are equal. With mobile-first indexing, mobile speed is what Google judges first — not desktop." } },
    { "@type": "Question", "name": "What is CLS in website performance?", "acceptedAnswer": { "@type": "Answer", "text": "CLS stands for Cumulative Layout Shift — a measure of how much a page visually jumps around while loading. A score under 0.1 is good. CLS happens when images load without defined dimensions, ads inject content, or fonts swap after render. It makes pages feel unstable and is a Core Web Vitals ranking factor." } },
    { "@type": "Question", "name": "How do I speed up my website on mobile?", "acceptedAnswer": { "@type": "Answer", "text": "To speed up a website on mobile: convert images to WebP and lazy load off-screen images, eliminate render-blocking scripts, use a CDN, minimize CSS and JavaScript, and upgrade to faster hosting. Mobile speed is judged separately from desktop and Google uses mobile speed first for ranking decisions." } },
    { "@type": "Question", "name": "What is lazy loading and does it help?", "acceptedAnswer": { "@type": "Answer", "text": "Lazy loading delays loading of off-screen images and videos until the user scrolls to them. It improves initial page load time because the browser only loads what is immediately visible. Enabling lazy loading on a typical local business website reduces initial page size by 40–60% and improves LCP scores significantly." } },
    { "@type": "Question", "name": "Does image size affect website speed?", "acceptedAnswer": { "@type": "Answer", "text": "Yes — images are the single biggest cause of slow websites, accounting for 60–70% of total page weight on most local business sites. An uncompressed hero image can be 2–5MB. The same image properly compressed to WebP format is typically 50–150KB — a 90% size reduction with no visible quality loss." } },
    { "@type": "Question", "name": "What is WebP and should I use it?", "acceptedAnswer": { "@type": "Answer", "text": "WebP is a modern image format developed by Google that produces images 25–35% smaller than JPEG and 26% smaller than PNG with equal or better visual quality. Google recommends WebP for all web images. Using WebP instead of JPEG or PNG is one of the easiest ways to improve PageSpeed scores immediately." } },
    { "@type": "Question", "name": "How do I know if my hosting is slow?", "acceptedAnswer": { "@type": "Answer", "text": "Check TTFB (Time to First Byte) using Google PageSpeed Insights. A TTFB over 600ms indicates a slow server. Shared hosting from GoDaddy, Bluehost, or HostGator typically produces TTFB of 800ms–2000ms. Managed hosting providers like Kinsta or WP Engine typically produce TTFB under 200ms." } },
    { "@type": "Question", "name": "What is a render-blocking script?", "acceptedAnswer": { "@type": "Answer", "text": "A render-blocking script is a JavaScript or CSS file that forces the browser to stop building the page until the file fully downloads. Common culprits are Google Tag Manager, analytics scripts, chat widgets, and advertising pixels loaded in the page head. Each render-blocking script adds 100–500ms to load time." } },
    { "@type": "Question", "name": "How do I pass Core Web Vitals?", "acceptedAnswer": { "@type": "Answer", "text": "To pass Core Web Vitals: get LCP under 2.5 seconds by optimizing images and upgrading hosting, get INP under 200ms by reducing JavaScript execution, and get CLS under 0.1 by setting image dimensions and avoiding layout shifts. Most local business sites can pass all three with image optimization, hosting upgrades, and script cleanup." } },
    { "@type": "Question", "name": "What is the difference between desktop and mobile speed scores?", "acceptedAnswer": { "@type": "Answer", "text": "Desktop and mobile scores are measured separately because mobile devices have slower processors and connections. A site can score 90 on desktop and 35 on mobile. Since Google uses mobile-first indexing, mobile score determines search rankings — not desktop score." } },
    { "@type": "Question", "name": "What is a CDN and do I need one?", "acceptedAnswer": { "@type": "Answer", "text": "A CDN (Content Delivery Network) stores copies of website files on servers worldwide so visitors load from the server closest to them. Cloudflare offers a free CDN that typically improves load times by 20–40% and adds DDoS protection. Most local business websites should be using a CDN." } },
    { "@type": "Question", "name": "How much does it cost to fix website speed?", "acceptedAnswer": { "@type": "Answer", "text": "Professional website speed optimization costs $300–$2,000 for a comprehensive one-time fix at a boutique agency. Enterprise agencies charge $1,800–$4,800 per month. Freelancers charge $100–$500 for basic work. Pricing depends on site size, platform, and depth of work required. Always ask for a flat fee rather than hourly billing to avoid surprises." } },
    { "@type": "Question", "name": "Who can fix my WordPress site speed?", "acceptedAnswer": { "@type": "Answer", "text": "WordPress speed specialists, local web agencies, and managed WordPress hosting providers all offer speed optimization services. Look for someone who addresses hosting, images, caching, and render-blocking scripts together — not just one issue in isolation. Ask for before and after PageSpeed scores as proof of results." } },
    { "@type": "Question", "name": "What does a website SEO cleanup include?", "acceptedAnswer": { "@type": "Answer", "text": "A comprehensive website SEO cleanup includes speed optimization, Core Web Vitals fixes, image conversion to WebP, 301 redirect cleanup, 404 error resolution, citation audit and correction, Google Business Profile optimization, and conversion tracking installation. The best cleanups also include FAQ and pricing pages built with schema markup to capture AI Overview and featured snippet traffic." } },
    { "@type": "Question", "name": "Why do citations matter for local SEO?", "acceptedAnswer": { "@type": "Answer", "text": "Citations — your business Name, Address, and Phone number listed across directories — must be identical everywhere for Google to trust your location data. Even small inconsistencies like 'St.' vs 'Street' or a missing suite number can prevent your business from appearing in Google's local 3-Pack. Citations are the number one reason local businesses fail to rank locally." } },
    { "@type": "Question", "name": "Why is my business not showing up in Google Maps?", "acceptedAnswer": { "@type": "Answer", "text": "The top reasons a business does not appear in Google Maps are an incomplete or unverified Google Business Profile, inconsistent citations across directories, insufficient reviews, a slow website, and proximity factors. Google's 3-Pack favors businesses with complete profiles, consistent NAP data, and strong local signals across the web." } },
    { "@type": "Question", "name": "How long does it take to fix a slow website?", "acceptedAnswer": { "@type": "Answer", "text": "Most website speed fixes are completed within 24 hours of approval. Image optimization, script cleanup, caching configuration, and Core Web Vitals fixes are typically done same day. Citation corrections take 2–4 weeks because each directory must be contacted individually. Google's Core Web Vitals scores update on a 28-day rolling average." } }
  ]
};

export default function Page() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <FaqClient />
    </>
  );
}
